### ISSUE TITLE
Roadmap of Genesis

### ISSUE THREAD

**Issue by axaluss** [arkOScloud/genesis#525]
It would be great to see where the project stands with regards to features and stability (alpha, beta, release...). A roadmap could provide an overview of the project status. i.e. an estimate to when "Warning – arkOS and its constituent software are still in development." will disappear from the homepage would help.

**Comment by Folatt** [comment]
It did have a roadmap. Then it's only developer got a job and the roadmap was removed because the project is moving at a glacieal pace.  I would love to work on it, under the condition that I can use two computers, one for watching youtube videos and one for arkOS development. I have yet to get the second one working and it's taking me months :disappointed:

**Comment by peakwinter** [comment]
Good news, I've cleared out some problems in my schedule and will have more time now to work on the project. I will be putting a roadmap back up on the main site soon :) Thanks for your patience guys!

**Comment by peakwinter** [comment]
We will now be publishing regular roadmaps on the blog, using Github milestones, and [on the forums too](https://bbs.arkos.io/t/2017-roadmap/2465).
